### ISSUE TITLE
Not auth with GitHub

### ISSUE THREAD

**Issue by a-alfonso** [visualgitio/LGit#71]
Hello.

I just donwloaded your "VisualGit" extension because i needeed a VB6 IDE solution to connect it to git and github.

The problems come when I try to upload a "test" proyect to my remote repository using the "push" button.
![image](https://user-images.githubusercontent.com/96050751/164405519-aa7e7fa6-33b4-422d-82ed-b993e9011670.png)

When i fullfill the next pop-up window it does not auth me, it just reload the pop-up again and again in a infinite loop without any error or waning message.
![image](https://user-images.githubusercontent.com/96050751/164405871-6d39c72a-d48f-4ff2-8973-b787913d49ab.png)

I'm using my github user and password. I am doing something wrong? Do i need to add/modify something in somewhere?

Regards.

**Comment by awilfox** [comment]
You can't use a GitHub password with HTTPS Git operations.  You'll need to [create a Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) and use that as the 'password' for your HTTPS operations.  This is to keep your account password secure and is a feature/limitation of GitHub, not Visual Git.

**Comment by a-alfonso** [comment]
Oh, now is working! A lot of thanks for the help

**Comment by NattyNarwhal** [comment]
Alternatively, you can use an SSH remote. There's no interface to set a key explicitly, but it'll use an agent you have configured; Pageant from PuTTY will work.
